name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  build:

    strategy:
      matrix:
        node-version: [20, 22, 23]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Enable pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install -r
      - name: Check coding standards
        run: npm run lint
      - name: Static analysis - check types
        run: npm run build
      - name: Test with coverage
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          env_vars: OS,NODE
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
